app: # 应用基本配置
  env : local # 环境名称
  port : 8080 # 服务监听端口号
  app_name:  ginfromerfram
  app_url : 127.0.0.1

  # YAML的键值对是由冒号和空格分开的，
  # 如果冒号不是半角，或者忘记加空格，就会出现无法识别的情况
  # 在确认冒号和空格没有问题的情况下，
  # 看一下是不是写了多余的不能识别的东西。
  # 比如YAML只支持单行“#”注释，不支持“//”这种注释方法